name: Test:org.apache.nifi.registry.security.ldap.tenants.LdapUserGroupProviderTest#testSearchUsersAndGroupsNoMembership
run-name: Known Flaky test
on: [push]
jobs:
  Test_Without_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Compiler
        run: mvn install -DskipTests -am -pl nifi-registry/nifi-registry-core/nifi-registry-framework
      - name: Test
        run: mvn test -pl nifi-registry/nifi-registry-core/nifi-registry-framework -Dtest=org.apache.nifi.registry.security.ldap.tenants.LdapUserGroupProviderTest#testSearchUsersAndGroupsNoMembership
        
  Test_With_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Compiler
        run: mvn install -DskipTests -am -pl nifi-registry/nifi-registry-core/nifi-registry-framework
      - name: Test
        run: mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -pl nifi-registry/nifi-registry-core/nifi-registry-framework -DnondexRuns=10 -Dtest=org.apache.nifi.registry.security.ldap.tenants.LdapUserGroupProviderTest#testSearchUsersAndGroupsNoMembership
